version: '3'

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PYTHONPATH: /workspace
    volumes:
      - ..:/workspace
    command: sleep infinity
    shm_size: 2gb
    networks:
      - met-webapp-network

networks:
  met-webapp-network:
    external: true
